receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost:3000"
            - "http://localhost:3001"
          allowed_headers: ["*"]

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

  resource:
    attributes:
      - key: environment
        from_attribute: deployment.environment
        action: insert
      - key: service.name
        from_attribute: service.name
        action: upsert

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 20

  prometheus:
    endpoint: "0.0.0.0:8888"
    
  # Uncomment and configure for production
  # otlp:
  #   endpoint: "your-observability-backend:4317"
  #   tls:
  #     insecure: false

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  
  pprof:
    endpoint: :1888
    
  zpages:
    endpoint: :55679

service:
  extensions: [health_check, pprof, zpages]
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]
      
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, prometheus]
      
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]