name: CODEOWNERS Validation

on:
  pull_request:
    paths:
      - '.github/CODEOWNERS'
  push:
    paths:
      - '.github/CODEOWNERS'

jobs:
  validate:
    name: Validate CODEOWNERS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate CODEOWNERS
        uses: mszostok/codeowners-validator@v0.7.4
        with:
          checks: "files,owners,duppatterns,syntax"
          experimental_checks: "notowned"